package com.mmall.model;

import java.util.Date;

public class PayInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.id
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.user_id
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.order_no
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.pay_platform
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private Integer payPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.platform_number
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private String platformNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.charge_amout
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private Long chargeAmout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.currentcy
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private String currentcy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.platform_status
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private String platformStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.create_time
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.update_time
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.meta_data
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    private String metaData;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public PayInfo(Integer id, Integer userId, Long orderNo, Integer payPlatform, String platformNumber, Long chargeAmout, String currentcy, String platformStatus, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.orderNo = orderNo;
        this.payPlatform = payPlatform;
        this.platformNumber = platformNumber;
        this.chargeAmout = chargeAmout;
        this.currentcy = currentcy;
        this.platformStatus = platformStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public PayInfo(Integer id, Integer userId, Long orderNo, Integer payPlatform, String platformNumber, Long chargeAmout, String currentcy, String platformStatus, Date createTime, Date updateTime, String metaData) {
        this.id = id;
        this.userId = userId;
        this.orderNo = orderNo;
        this.payPlatform = payPlatform;
        this.platformNumber = platformNumber;
        this.chargeAmout = chargeAmout;
        this.currentcy = currentcy;
        this.platformStatus = platformStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.metaData = metaData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public PayInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.id
     *
     * @return the value of mmall_pay_info.id
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.id
     *
     * @param id the value for mmall_pay_info.id
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.user_id
     *
     * @return the value of mmall_pay_info.user_id
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.user_id
     *
     * @param userId the value for mmall_pay_info.user_id
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.order_no
     *
     * @return the value of mmall_pay_info.order_no
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.order_no
     *
     * @param orderNo the value for mmall_pay_info.order_no
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.pay_platform
     *
     * @return the value of mmall_pay_info.pay_platform
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public Integer getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.pay_platform
     *
     * @param payPlatform the value for mmall_pay_info.pay_platform
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setPayPlatform(Integer payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.platform_number
     *
     * @return the value of mmall_pay_info.platform_number
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public String getPlatformNumber() {
        return platformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.platform_number
     *
     * @param platformNumber the value for mmall_pay_info.platform_number
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setPlatformNumber(String platformNumber) {
        this.platformNumber = platformNumber == null ? null : platformNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.charge_amout
     *
     * @return the value of mmall_pay_info.charge_amout
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public Long getChargeAmout() {
        return chargeAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.charge_amout
     *
     * @param chargeAmout the value for mmall_pay_info.charge_amout
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setChargeAmout(Long chargeAmout) {
        this.chargeAmout = chargeAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.currentcy
     *
     * @return the value of mmall_pay_info.currentcy
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public String getCurrentcy() {
        return currentcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.currentcy
     *
     * @param currentcy the value for mmall_pay_info.currentcy
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setCurrentcy(String currentcy) {
        this.currentcy = currentcy == null ? null : currentcy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.platform_status
     *
     * @return the value of mmall_pay_info.platform_status
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public String getPlatformStatus() {
        return platformStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.platform_status
     *
     * @param platformStatus the value for mmall_pay_info.platform_status
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setPlatformStatus(String platformStatus) {
        this.platformStatus = platformStatus == null ? null : platformStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.create_time
     *
     * @return the value of mmall_pay_info.create_time
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.create_time
     *
     * @param createTime the value for mmall_pay_info.create_time
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.update_time
     *
     * @return the value of mmall_pay_info.update_time
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.update_time
     *
     * @param updateTime the value for mmall_pay_info.update_time
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.meta_data
     *
     * @return the value of mmall_pay_info.meta_data
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public String getMetaData() {
        return metaData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.meta_data
     *
     * @param metaData the value for mmall_pay_info.meta_data
     *
     * @mbg.generated Thu Nov 22 12:27:22 PST 2018
     */
    public void setMetaData(String metaData) {
        this.metaData = metaData == null ? null : metaData.trim();
    }
}