package com.mmall.model;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Tue Nov 06 01:18:41 PST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Tue Nov 06 01:18:41 PST 2018
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Tue Nov 06 01:18:41 PST 2018
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Tue Nov 06 01:18:41 PST 2018
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Tue Nov 06 01:18:41 PST 2018
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Tue Nov 06 01:18:41 PST 2018
     */
    int updateByPrimaryKey(Shipping record);

    int updateByUserIdShippingId(Shipping record);

    int deleteByUserIdShippingId(@Param("userId")Integer userId, @Param("shippingId")Integer shippingId);

    Shipping selectByUserIdShippingId(@Param("userId")Integer userId, @Param("shippingId")Integer shippingId);

    List<Shipping> selectByUserId(Integer userId);
}